# MathJax Configuration
mathjax:
  enable: true
  input: "tex" # Use TeX input format
  output: "html" # Render as HTML


markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false


title: <your title>
